services:
  - type: web
    name: commentium-api
    env: docker
    build:
      dockerfilePath: Commentium.API/Dockerfile
      contextPath: .
    ports:
      - "5000:5000"
      - "5001:5001"
    envVars:
      - key: DefaultConnection
        value: "Server=host.docker.internal,1433;Database=CommentiumDb;User Id=sa;Password=Password12345!;Trust Server Certificate=True;"
      - key: Redis
        value: "commentium.cache:6379"
      - key: MessageBroker_Host
        value: "amqp://commentium-queue:5672"
      - key: MessageBroker_Username
        value: "guest"
      - key: MessageBroker_Password
        value: "guest"
      - key: CORS_ORIGIN_URL
        value: "http://localhost:4200"
    services:
      depends_on:
        - commentium-mq
        - sqlserver

  - type: background
    name: commentium-cache
    env: docker
    image: redis:latest
    containerName: commentium-cache
    restartPolicy: always
    ports:
      - "6379:6379"

  - type: background
    name: commentium-mq
    env: docker
    image: rabbitmq:3.11.7-management
    containerName: commentium-queue
    hostname: commentium-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - mqdatavolume:/var/lib/rabbitmq
      - mqlogvalume:/var/log/rabbitmq
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: "guest"
      - key: RABBITMQ_DEFAULT_PASS
        value: "guest"

  - type: web
    name: commentium-client
    env: docker
    build:
      dockerfilePath: Commentium.Client/Dockerfile
      contextPath: .
    ports:
      - "4200:4200"

  - type: database
    name: commentium-database
    env: docker
    image: mcr.microsoft.com/mssql/server:2022-latest
    containerName: commentium-database
    envVars:
      - key: SA_PASSWORD
        value: "Password12345!"
      - key: ACCEPT_EULA
        value: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
  mqdatavolume:
  mqlogvalume: